apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberos-admission
  labels:
    app.kubernetes.io/name: kuberos
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - get
      - update
