apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kuberos-admission
  namespace: kuberos
  labels:
    app.kubernetes.io/name: kuberos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kuberos-admission
subjects:
  - kind: ServiceAccount
    name: kuberos-admission
    namespace: kuberos
