apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kuberos-admission
  namespace: kuberos
  labels:
    app.kubernetes.io/name: kuberos
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - create
